#!/bin/env sh

# Atlas Health
_start_env() {
    source ./venv/bin/activate
    tree --matchdirs -I "venv|__pycache__|tests"
    if [[ $1 == "-p" ]]; then
        charm .
    fi
}

match2() {
    pushd ~/workspace/atlas_health/match2 >/dev/null 2>1
    _start_env $@
}

flow() {
    pushd ~/workspace/atlas_health/flow >/dev/null 2>1
    _start_env $@
}
