#!/bin/env sh

# Built-In
alias ...="cd ../.."
alias ....="cd ../../.."

cdl() { cd "$@" && ls; }
cdls() { cd "$@" && ls; }
cdla() { cd "$@" && ls -a; }
cdlal() { cd "$@" && ls -lahF; }
cdlla() { cd "$@" && ls -lahF; }

alias senv="env |sort"
alias dim="echo $(tput cols)x$(tput lines)"

# View SSH Hosts
alias sshs="\\cat ~/.ssh/config | grep \"Host \""

# Overwrite default variables
command -v bat >/dev/null && CAT_TYPE=bat
alias cat="${CAT_TYPE:-cat}"  # print file with syntax highlighting.
alias cat="bat"

command -v gls >/dev/null && LS=gls && LSOPTS="--color=auto --group-directories-first"
alias grep="grep --color=auto"  # highlight desired sequence.

alias ls="${LS:-ls} -h $LSOPTS"
alias sl="${LS:-ls} -h $LSOPTS"
alias la="${LS:-ls} -ah $LSOPTS"
alias lsa="${LS:-ls} -ahF $LSOPTS"
alias lsl="${LS:-ls} -lhF $LSOPTS"
alias lsal="${LS:-ls} -lahF $LSOPTS"
alias lsla="${LS:-ls} -lahF $LSOPTS"

alias mkdir="mkdir -pv"  # makes parent directories if necessary, verbosely

cop() {
    case "$OSTYPE" in
        darwin*) \cat $1 |pbcopy ;;
        linux*) xclip -selection c $1 ;;
        *) echo "Unrecognized OSTYPE" && exit 1 ;;
    esac
    # if [[ "$OSTYPE" == "darwin"* ]]; then

    # elif [[ "$OSTYPE" == "linux-gnu" ]]; then

    # fi
}

