#!/bin/env sh

# File shortcuts
alias arc="vim ~/._aliasrc"
alias brc="vim ~/.bashrc"
alias vrc="vim ~/.vimrc"
alias zrc="vim ~/.zshrc"
alias bpr="vim ~/.bash_profile"
alias pro="vim ~/.profile"
alias sco="vim ~/.ssh/config"
alias sbp="source ~/.bash_profile"
alias rez="exec zsh"

