#!/bin/env sh

# Go
go-get-help() {
    mkdir -p ${HOME}/workspace/ws_go
    pushd ${HOME}/workspace/ws_go
    git clone https://github.com/mmcgrana/gobyexample.git
    go get github.com/russross/blackfriday
    ./gobyexample/tools/build
    open ./gobyexample/public/index.html
}
alias go-help="open ${HOME}/workspace/ws_go/gobyexample/public/index.html || go-get-help"
